### ISSUE TITLE
GitHub Issue Slack Link Incorrect

### ISSUE THREAD

**Issue by agardnerIT** [k8sgpt-ai/k8sgpt#376]
I wanted to open a question / feature request so I began creating an issue.

The checkboxes directed me to ask first on Slack. However, the link takes me to the "generic" page which insists on an `@k8sgpt.ai` email address to register.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/26523841/236058507-e887061c-b812-463f-8af9-0d397e40560d.png">

## Fix

The link should use the shared invite code and then anyone can register.

**Comment by YashPimple** [comment]
@AlexsJones @agardnerIT  would like to know is this issue has been resolved ? since I'm facing the same issue and unable to join Slack

**Comment by YashPimple** [comment]
Incorrect Slack Link in .github/README.md Community Section - Update Required

Description:
@AlexsJones @agardnerIT @thschue I encountered an same issue #376 while joining Slack for K8sgpt. In the Home screen of the K8sgpt GitHub repository (https://github.com/k8sgpt-ai), the [.github/README.MD](https://github.com/k8sgpt-ai/.github/blob/main/profile/README.md) file, under the community section, the displayed Slack link is incorrect. It redirects new contributors to a page that insists on an `@k8sgpt.ai` email address, instead of providing the correct invite code link for Slack as documented in the [contributing-guide] getting Started section (https://github.com/k8sgpt-ai/k8sgpt/blob/main/CONTRIBUTING.md).

Furthermore, the attached screenshot shows the incorrect link placement and destination.
<img width="747" alt="image" src="https://github.com/k8sgpt-ai/k8sgpt/assets/97302447/a3a8b584-17ad-4da0-a4f5-25a79852d502">

Steps to reproduce:
To resolve this issue, we need to update and document the correct invite link for Slack in the [.github/README.MD](https://github.com/k8sgpt-ai/.github/blob/main/profile/README.md) community section .

**Comment by YashPimple** [comment]
Sure @AlexsJones will open a PR addressing the above issue
