### ISSUE TITLE
Log analyzer failed with multiple containers in the pod  

### ISSUE THREAD

**Issue by lili-wan** [k8sgpt-ai/k8sgpt#884]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

Latest

### Steps to reproduce

1. Run 'k8sgpt analyze --filter Log --namespace <your-namespace>' that has a pod running with multiple containers  
2. You will get the following error
```
- Error: Error the server rejected our request for an unknown reason (get pods efs-csi-node-us-west-2b-n7dwf) from Pod efs-csi-node-us-west-2b-n7dwf
```

### Expected behaviour

The Log filter should scan all the containers and return the error logs if there is any

### Actual behaviour

The Log filter returns a server error

**Comment by VaibhavMalik4187** [comment]
@AlexsJones, I was going through the `log` analyzer when I noticed that the following line of code would fetch all the pods(running and stopped) in a given namespace.
https://github.com/k8sgpt-ai/k8sgpt/blob/78126b2328c1b3f81a269d203e86128104050010/pkg/analyzer/log.go#L44

However, the comment states that it only fetches pods that are not running. Is this intentional?
https://github.com/k8sgpt-ai/k8sgpt/blob/78126b2328c1b3f81a269d203e86128104050010/pkg/analyzer/log.go#L43

**Comment by lili-wan** [comment]
I think the comment is not correct, it does fetch logs from all the pods, but the issue is if the pod has multiple containers, it will return error because it does not fetch the log from individual container
