### ISSUE TITLE
undefined: AnalyzerErrorsMetric 

### ISSUE THREAD

**Issue by Aman123lug** [k8sgpt-ai/k8sgpt#949]
I cloned the repository, 
I run test coverage in GO-lang by this command 
``` 
go test -cover .\deployment.go
```
I wanted to check the coverage of each file that contains the _test.go 

It will be through error :
![image](https://github.com/k8sgpt-ai/k8sgpt/assets/94223645/e74d7365-0d54-4f20-ad13-38d3b217f593)

And when I run this command:
```
go test -cover
```
![image](https://github.com/k8sgpt-ai/k8sgpt/assets/94223645/412f43c1-5fca-4136-a9c7-e332b5610b90)
 It works very well
 
 This is not only for the deployment.go for all file

**Comment by amitamrutiya2210** [comment]
Hey @Aman123lug, 

Go uses packages as the unit for testing and coverage, not individual files. The tests for a file in a package are usually written in a corresponding `_test.go` file, and `go test` runs all tests in the package. 

The errors you encountered occurred because you attempted to run tests on a specific file that relies on another file within the same package. The selected file has dependencies on other files, and running tests in isolation may result in these errors.

If you want to get a detailed coverage profile that shows the coverage for each function, you can use the `-coverprofile` flag:

```
go test -coverprofile=coverage.out your_package_name
``` 

This will create a file named `coverage.out` that contains the coverage profile. You can view the details in this file with the go tool cover command:

```
go tool cover -func=coverage.out
``` 

This will print the coverage for each function in the package.

**Comment by Aman123lug** [comment]
Thanks @amitamrutiya2210 for the detailed explanation
